server:
  port: 8075

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/rahul2011421/Hotel-Rating-Application-Configuration
          clone-on-start: true
