server:
  port: 8073

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Maveric


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update